spring:
  datasource:
    url: jdbc:postgresql://localhost:4000/test
    driver-class-name: org.postgresql.Driver
    username: user
    password: pass

server:
  port: 3001
  servlet:
    context-path: /v1/core-api

jwt:
  secret: BvPHGM8C0ia4uOuxxqPD5DTbWC9F9TWvPStp3pb7ARo0oK2mJ3pd3YG4lxA9i8bj6OTbadwezxgeEByY

core:
  user-paths:
    - "/person/reset"
    - "/person/deleteSelf"
    - "/person/updateRestaurantStatus"
    - "/person/id"
    - "/person/name"
    - "/person/validate"